apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-kubernetes-on-aws
  labels:
    app: nodejs-kubernetes-on-aws
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-kubernetes-on-aws
  template:
    metadata:
      labels:
        app: nodejs-kubernetes-on-aws
    spec:
      containers:
        - name: nodejs-kubernetes-on-aws
          image: amromar/nodejs-kubernetes-on-aws
          ports:
            - containerPort: 80
