apiVersion: v1
kind: Service
metadata:
  name: nodejs-kubernetes-on-aws
  labels:
    run: nodejs-kubernetes-on-aws
spec:
  ports:
    - port: 80
      protocol: TCP
  selector:
    run: nodejs-kubernetes-on-aws
